### ISSUE TITLE
create title for tags

### ISSUE THREAD

**Issue by ekici23** [v17development/flarum-seo#15]
https://flarumtr.com/t/destek Consider URL. The `<head><title>Flarum Türkiye</title></ head>` does not create a page description for the tag. should be in the `<head> <title> Destek-Flarum Türkiye </ title> </ head>`

However, the same does not apply to pages. See:

https://flarumtr.com/p/3-iletisim

```
<head>
<title>İletişim - Flarum Türkiye</title>
</head>
```

**Comment by jaspervriends** [comment]
Should be fixed in the new release!
