### ISSUE TITLE
Empty value

### ISSUE THREAD

**Issue by Monsterkill** [v17development/flarum-seo#18]
Flarum 0.1.0-beta.9
vendor\v17development\flarum-seo\src\Managers\QADiscussion.php
`$this->firstPost->getAttribute('contentHtml')` empty value

**Comment by jaspervriends** [comment]
Hi there, thanks for creating this issue.

Can you explain in what situations this happens? And does this crash the page or only in warnings in the logs?

Let me know!

**Comment by Monsterkill** [comment]
it's always, contentHtml value not present in the `attributes` key in the `$this->firstPost` array
