### ISSUE TITLE
Unable to render Twitter card preview

### ISSUE THREAD

**Issue by codfx** [v17development/flarum-seo#21]
I am running on the latest extension (1.0.2) and when I try to preview Twitter card it shows me the below log:

```
INFO:  Page fetched successfully
INFO:  15 metatags were found
INFO:  twitter:card = summary tag found
ERROR: Possibly invalid value (if specified) (twitter:title)
ERROR: Possibly invalid value (if specified) (og:title)
ERROR: Possibly invalid value (if specified) (twitter:text:title)
```

**Comment by jaspervriends** [comment]
Hi @codfx , can you check the source of your webpage, do the parameters of twitter exist and are they filled in?

The log is from https://cards-dev.twitter.com/validator , right?

**Comment by codfx** [comment]
Hi @jaspervriends , below Twitter parameters are there in the source code:


```
<meta name="twitter:card" content="summary">
<meta name="twitter:image" content="...">
<meta name="twitter:description" content="...">
```

*I have replaced original texts with "..."

Yes, the log is from Twitter card validator. 

I'm happy to share my flarum URL if you want to find more information.

**Comment by codfx** [comment]
Hi @jaspervriends , below Twitter parameters are there in the source code:


```
<meta name="twitter:card" content="summary">
<meta name="twitter:image" content="...">
<meta name="twitter:description" content="...">
```

*I have replaced original texts with "..."

Yes, the log is from Twitter card validator. 

I'm happy to share my flarum URL if you want to find more information.

**Comment by LiljebergXYZ** [comment]
@jaspervriends I just ran into the same issue. I've looked at the code and noticed that you only add the `og:title` and `twitter:title` tags on the discussion pages. I believe we should also show this on the frontpage, set to the website name. Is this anything you would be interested in fixing, or should I provide a PR instead?

**Comment by jaspervriends** [comment]
I've updated the plugin, are you able to test the Twitter cards again? @LiljebergXYZ @codfx 

It works for Twitter and WhatsApp (just tested it)
