### ISSUE TITLE
Error on suggestedAnswer in google Search

### ISSUE THREAD

**Issue by Hydrog3n** [v17development/flarum-seo#27]
Hello, thank you for your ext. 

I have some errors on google console when a discussion.

This happens on page with only Stream post like edit title, change tags, etc

You can found an example here: https://mondedie.fr/d/10326-[Tuto]-Certificat-Wildcard-et-serveur-DNS-autoritaire-NSD/DNSSEC-Docker

I see in the code you get all posts and you count. Can you get only the "real" post? 

https://github.com/v17development/flarum-seo/blob/f691c4aed1efe476aecd3b6049aca1178f805cd5/src/Managers/QADiscussion.php#L84

**Comment by jaspervriends** [comment]
Should be fixed in the next version
