### ISSUE TITLE
Use display name instead of username for author and profile

### ISSUE THREAD

**Issue by clarkwinkelmann** [v17development/flarum-seo#3]
Nice extension.

I haven't tried it yet but went through the code to check how it's working.

I notice you always use the `username` user property for the meta author name.

Beta 8 introduced the `display_name` user property. So far I don't think any extension uses this feature but you might already want to switch to that property so you're ready. For now `display_name` is always the same as `username` unless an extension provides another one.

I'll be able to provide a PR in the future but I already wanted to make you aware of it :wink:

**Comment by jaspervriends** [comment]
I wasn't aware of the ``display_name`` user property, thanks for letting me know! I look forward to your PR :)
