### ISSUE TITLE
Schema headline wrong encode on cyrillic string

### ISSUE THREAD

**Issue by vlntsolo** [v17development/flarum-seo#34]
Hi, I just tested my post with Cyrillic content with Google testing tool and noticed that flarum-seo encodes description content to headline in schema, so the headline prop duplicates description.
https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Fq.quarks.app%2Fuk%2Fd%2F20-yak-diznatisya-optimalnu-vitratu-resursu

That's strange since description string is parsed and displayed properly.

**Comment by jaspervriends** [comment]
I've fixed the headline issue, it should indeed display the discussion title instead of the description. I'll update the extension later today 😄
