### ISSUE TITLE
Extention "FoF Filter" broken

### ISSUE THREAD

**Issue by RubixMeCube** [v17development/flarum-seo#39]
The extention **FoF Filter** is broken. It shows up things like
random_text.random_text.button_hello. Could you fix it? Thanks!

**Comment by jaspervriends** [comment]
Hi!

This extension is not related to the FoF Filter extension.

I'd like to recommend you to go to the GitHub of FriendsOfFlarum and post your issue there or create a topic on discuss.flarum.org :)

Cheers
