### ISSUE TITLE
PHP notice error on discussion page about passing by reference

### ISSUE THREAD

**Issue by datitisev** [v17development/flarum-seo#4]
```php
Notice: Only variables should be passed by reference in /Users/david/Sites/flarum-latest/vendor/v17development/flarum-seo/src/Managers/QADiscussion.php on line 82
```

- **Flarum**: `dev-master`
- **PHP**: 7.1.25
- **MySQL**: 5.7.24

https://github.com/v17development/flarum-seo/blob/0.2-beta/src/Managers/QADiscussion.php#L82

**Comment by jaspervriends** [comment]
I've updated the code, issue should be solved in the next update. Thanks for letting me know!

**Comment by datitisev** [comment]
@jaspervriends Yep! I can confirm it has been fixed in `dev-master`, no longer able to reproduce. Thanks!

By the way, you may want to consider using milestones and have an open milestone for the next release, but still close this issue because it has been fixed. :+1:
