### ISSUE TITLE
broke Dashboard in B15

### ISSUE THREAD

**Issue by Am4rok** [v17development/flarum-seo#43]
![Capture d’écran 2020-12-21 012330](https://user-images.githubusercontent.com/76412702/102728274-34988e80-432b-11eb-96a1-1de5cf26f879.jpg)

**Comment by jaspervriends** [comment]
I wrongly tagged the branch, please update to version 1.5.1. This one contains the actual update

**Comment by Am4rok** [comment]
it's with the 1.5.1 version ;)

**Comment by jaspervriends** [comment]
> it's with the 1.5.1 version ;)

Are you sure? Could you verify you're running version 1.5.1 and not 1.5.0? Because, the 'Search Engine Optimalization' menu item has been removed, and I do see that in your screenshot
