### ISSUE TITLE
Description tag included BBcode

### ISSUE THREAD

**Issue by bingit2** [v17development/flarum-seo#5]
Issue first reported here https://discuss.flarum.org/d/18316-flarum-seo/12

Would also love the option to remove the description tag altogether. I prefer the bot picks up relevant description from the page instead.

**Comment by bingit2** [comment]
I thought the QAPage setting will only be turned on if I have the QA extension. I dont want the QAPage format for my SEO.

**Comment by jaspervriends** [comment]
You can turn that off: https://github.com/v17development/flarum-seo#default-question-answer-results-for-discussions

**Comment by jaspervriends** [comment]
Updated plugin with a fix! You can update to 0.3-beta :)
