### ISSUE TITLE
set answerCount to 0 for unsolved topics

### ISSUE THREAD

**Issue by Hari-Bonda** [v17development/flarum-seo#59]
if the best answer is not selected set answerCount to 0

 : As per Google’s doc we need to set answerCount to 0 for unsolved topics

which means for all those no best answer posts answer count would be 0

reference link https://meta.discourse.org/t/either-acceptedanswer-or-suggestedanswer-should-be-specified/111809

https://developers.google.com/search/docs/data-types/qapage

discussion link https://discuss.flarum.org/d/18316-flarum-seo/426

![](https://i.imgur.com/cZRZgJX.png)
![](https://i.imgur.com/PjdRK1Q.png)

**Comment by jaspervriends** [comment]
Thanks again, my mistake, will be fixed in the next version!

**Comment by jaspervriends** [comment]
Should be fixed in version 2.0 that will be released soon! Thanks for reporting!
