### ISSUE TITLE
Q&A Metadata should respect "best answer" permission model to avoid Google crawler errors

### ISSUE THREAD

**Issue by eddiewebb** [v17development/flarum-seo#70]
>When you have the extension 'best answer' installed and enabled on your forum, it will mark the discussion as 'answered' on the search results and redirect the user to that specific post. 

Awesome!  However, 

Per the plugin's authors, "FOF Best Answers" let's you choose only certain tags to allow "best answer" by setting permissions (see https://github.com/FriendsOfFlarum/best-answer/issues/35).  

![permission in best nswer plugin limiting to certain tags](https://user-images.githubusercontent.com/16573496/128420161-4ee81685-6d2e-44ea-b375-705f7b8c23c6.png)

But when doing that this plugin still marks **all discussions** as Q&A, causing Google to be angry.

<img width="1120" alt="Screen Shot 2021-08-06 at 4 32 57 PM" src="https://user-images.githubusercontent.com/5262154/128568086-5fa274eb-49b4-4c7e-82a9-57234d8e2706.png">

I would like this plugin to check permission and only apply to tags where ability to mark "best answer" is open to members OR just let us define the tags to apply the `Q&A` type vs `ForumDiscussion` type

Thanks for the great plugin!

**Comment by ramesh-dada** [comment]
@jaspervriends Yes please fix this issue it's a big pain.

**Comment by jaspervriends** [comment]
Will be fixed in 2.0 which will be released soon. Thanks for reporting!
