### ISSUE TITLE
 Container was not yet initialized Error? setTitle

### ISSUE THREAD

**Issue by ConceptLabFE** [v17development/flarum-seo#73]
Hi,

I have very limited experience with this. How do I fix this error? Please help. 

flarum.ERROR: Exception: V17Development\FlarumSeo\Extend::setTitle(..): Container was not yet initialized. in /app/vendor/v17development/flarum-seo/src/Extend.php:196
Stack trace:

**Comment by jaspervriends** [comment]
Will be fixed in version 2.0 where I'm currently working on. Thanks for reporting!
