### ISSUE TITLE
Performance issues in busy forums with the likes extension

### ISSUE THREAD

**Issue by SychO9** [v17development/flarum-seo#76]
Hello! very useful extension for the ecosystem!

**Issue**
Someone reported a performance problem with what they believed was the `flarum/likes` extension: https://discuss.flarum.org/d/30913-huge-performance-problem-refreshing-takes-20sec-or-longer/. However, having looked into it, the problem stems from this extension, which was confirmed after enabling/disabling this extension.

These are the readings from clockwork:
![Screenshot from 2022-07-16 21-08-05](https://user-images.githubusercontent.com/20267363/179370736-64469edd-1b74-443a-81b2-4f8e7c10bba0.png)
![Screenshot from 2022-07-16 20-52-55](https://user-images.githubusercontent.com/20267363/179370737-71998808-2c49-4ac6-bc28-bb70ef96de37.png)

I am not familiar with the source code, but a quick glance suggests the following:
* When a discussion is loaded, **all** of its posts are queried (https://github.com/v17development/flarum-seo/blob/master/src/Managers/QADiscussion.php#L73).
* For each post, all the likes are queried (https://github.com/v17development/flarum-seo/blob/master/src/Managers/QADiscussion.php#L175).

In a busy forum this can easily lead to significant performance issues.

**Possible Solutions**
I'm not familiar with the targetted behavior, but I'd look into these:
- Do **all** posts need to be loaded?
- For the likes count, instead of counting resulting queried models. Include the count with the initial posts query (https://laravel.com/docs/9.x/eloquent-relationships#relationship-counting-and-custom-select-statements).
- If this only occurs when a certain setting is ON, display a warning on the UI next to the specific setting explaining the dangers.

Thanks.

**Comment by jaspervriends** [comment]
Thanks for reporting! Will be fixed in 2.0 which will be released soon 🚀

**Comment by edgeinfinity1** [comment]
v2.0.x of this extension still causes a +50~100% loading time on fresh-loading or reloading a discussion comparing to loading through API. Could this be further optimized?
