### ISSUE TITLE
Deprecated - Fatal error with empty categories

### ISSUE THREAD

**Issue by skariko** [v17development/flarum-seo#87]
Hello,
if you try to access an empty (first or secondary) section you get this error with PHP 8.1:

`Deprecated: DateTime::__construct(): Passing null to parameter #1 ($datetime) of type string is deprecated in /XXXXXXXXXXXXXXXXXXX/forum.lealternative.net/vendor/v17development/flarum-seo/src/Managers/Tag.php on line 48

Fatal error: Uncaught Laminas\HttpHandlerRunner\Exception\EmitterException: Output has been emitted previously; cannot emit response in /XXXXXXXXXXXXXXXXXXX/forum.lealternative.net/vendor/laminas/laminas-httphandlerrunner/src/Exception/EmitterException.php:20 Stack trace: #0 /XXXXXXXXXXXXXXXXXXX/forum.lealternative.net/vendor/laminas/laminas-httphandlerrunner/src/Emitter/SapiEmitterTrait.php(42): Laminas\HttpHandlerRunner\Exception\EmitterException::forOutputSent() #1 /XXXXXXXXXXXXXXXXXXX/forum.lealternative.net/vendor/laminas/laminas-httphandlerrunner/src/Emitter/SapiEmitter.php(21): Laminas\HttpHandlerRunner\Emitter\SapiEmitter->assertNoPreviousOutput() #2 /XXXXXXXXXXXXXXXXXXX/forum.lealternative.net/vendor/laminas/laminas-httphandlerrunner/src/RequestHandlerRunner.php(75): Laminas\HttpHandlerRunner\Emitter\SapiEmitter->emit(Object(Laminas\Diactoros\Response\HtmlResponse)) #3 /XXXXXXXXXXXXXXXXXXX/forum.lealternative.net/vendor/flarum/core/src/Http/Server.php(45): Laminas\HttpHandlerRunner\RequestHandlerRunner->run() #4 /XXXXXXXXXXXXXXXXXXX/forum.lealternative.net/index.php(26): Flarum\Http\Server->listen() #5 {main} thrown in /XXXXXXXXXXXXXXXXXXX/forum.lealternative.net/vendor/laminas/laminas-httphandlerrunner/src/Exception/EmitterException.php on line 20`

Try to go here: https://lealternative.forum/t/news and reload page.

**Comment by davwheat** [comment]
Production servers shouldn't have deprecation warnings enabled.

**Comment by skariko** [comment]
> Production servers shouldn't have deprecation warnings enabled.

that's true but is a shared hosting and I can't modify php.ini
Do you know if there is another way to workaround this?
