### ISSUE TITLE
PHP Deprecated

### ISSUE THREAD

**Issue by treybowman** [v17development/flarum-seo#88]
Getting this error in log.

`[24-May-2024 17:34:35 UTC] PHP Deprecated:  DateTime::__construct(): Passing null to parameter #1 ($datetime) of type string is deprecated in /home/REDACTED/REDACTED/vendor/v17development/flarum-seo/src/Managers/Tag.php on line 48`

**Comment by jaspervriends** [comment]
Should be fixed with version 2.0 by now :)
