### ISSUE TITLE
Add NOINDEX tag to prevent certain content from being indexed on search engines

### ISSUE THREAD

**Issue by medelinor-1** [v17development/flarum-seo#96]
Hello

_Please note that I use translation_.

This SEO extension is very useful, one of the things that I think will be useful to most of its users is the **NOINDEX tag** in the options.

The NOINDEX tag enables search engines to prevent indexing content that is specified with this tag.

What do you think about **adding an option that appears to the admin in the discussion options** where the post can be specified with the NOINDEX tag:

`<meta name="robots" content="noindex">`
or
`<meta name="googlebot" content="noindex">`

> **`noindex`** is a rule set with either a **`<meta>`** tag or HTTP response header and is used to prevent indexing content by search engines that support the **`noindex`** rule, such as Google. When Googlebot crawls that page and extracts the tag or header, Google will drop that page entirely from Google Search results, regardless of whether other sites link to it.
> More information [about the NOINDEX tag](https://developers.google.com/search/docs/crawling-indexing/block-indexing?hl=en)

Thank you

**Comment by jaspervriends** [comment]
Hey there! Thanks for opening this issue!

Since version 2.0 it's possible to disallow indexing the pages per discussion. As soon you open the SEO settings you can open the 'Robots' dropdown and disable the setting.

Is this what you were looking for?

![image](https://github.com/user-attachments/assets/8a895b0e-07a1-4ae6-8050-b696f30c4d8a)

**Comment by medelinor-1** [comment]
Hi again, thanks for your response

This is what the extension page looks like to me, I have a forum hosted on Flarom, I don't know if your new version will be coming to Flarom-hosted forums soon or if it's a private hosting issue:

![SEO Ext](https://github.com/user-attachments/assets/d50f1a3f-249a-4af3-97b7-151d81b5c3af)


Is this what you were looking for? To some extent yes.
I meant for there to be an option under "Discussion Options" that allows you to prevent unwanted discussions from being indexed.

**Comment by medelinor-1** [comment]
I found the setting now.

Thank you very much.

That's exactly what I meant.

**Comment by jaspervriends** [comment]
Awesome, thanks for letting us know! Enjoy the update 🚀
